-- drop table Users;
-- drop table Animes;
-- drop table Comments;
-- drop table Posts;

CREATE TABLE Animes
(
    Id          INT PRIMARY KEY GENERATED by default as identity,
    Name        VARCHAR(255) NOT NULL,
    Author      VARCHAR(255) NOT NULL,
    Description TEXT         NOT NULL,
    ImageUrl    VARCHAR(1000)
);

CREATE TABLE Users
(
    Id              INT PRIMARY KEY GENERATED by default as identity,
    Login           VARCHAR(50) NOT NULL,
    Password        VARCHAR(50) NOT NULL,
    Age             INTEGER,
    Mobile          VARCHAR(50),
    FavoriteAnimeId INTEGER REFERENCES Animes (Id) ON DELETE CASCADE
);

--Пост с аниме. Как правильно привязать комменты?
CREATE TABLE Posts
(
    Id           INTEGER PRIMARY KEY GENERATED by default as identity,
    PostAuthorId INTEGER REFERENCES Users (Id)                    NOT NULL,
    AnimeId      INTEGER REFERENCES Animes (Id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE Comments
(
    Id              INTEGER PRIMARY KEY GENERATED by default as identity,
    CommentAuthorId INTEGER REFERENCES Users (Id) NOT NULL,
    PostId          INTEGER REFERENCES Posts (Id) NOT NULL,
    Description     TEXT                      NOT NULL,
    DateOfCreation  DATE                      NOT NULL
);








